name: Lint and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  node-version: 20
  pnpm-version: 9.12.1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm-version }}
          run_install: false

      - name: Setup Node.js with pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # - name: Generate Prisma Client
      #   run: pnpm prisma generate

      - name: Run ESLint
        run: pnpm run lint

  tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs:
      lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm-version }}
          run_install: false

      - name: Setup Node.js with pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Tests
        run: pnpm run test